name: Deploy Sileo Repo

on:
  push:
    branches:
      - main  # å½“æŽ¨é€åˆ° main åˆ†æ”¯æ—¶è§¦å‘

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dpkg-scanpackages
      run: sudo apt-get update && sudo apt-get install -y dpkg-dev

    - name: Generate Packages file
      run: dpkg-scanpackages -m ./debs > Packages

    - name: Compress Packages file
      run: |
        bzip2 -fks Packages
        gzip -fk Packages

    - name: Create Release file
      run: |
        echo "Origin: ðŸ’«Axs proâœ¨" > Release
        echo "Label: ðŸ’«Axs proâœ¨" >> Release
        echo "Suite: stable" >> Release
        echo "Version: 1.0" >> Release
        echo "Codename: ðŸ’«Axs proâœ¨" >> Release
        echo "Architectures: iphoneos-arm64 iphoneos-arm64e" >> Release
        echo "Components: main" >> Release
        echo "Description: è‡ªç”¨æ’ä»¶åˆ†äº«ï¼Œæœ‰é—®é¢˜è¯·å¸è½½ï¼ï¼ï¼" >> Release

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.PAT }}
        publish_dir: ./  # éƒ¨ç½²æ•´ä¸ªä»“åº“
