name: Update Packages on main

on:
  push:
    branches:
      - main
    paths:
      - 'debs/**'  # ç›‘å¬ debs ç›®å½•ä¸‹çš„æ–‡ä»¶å˜åŒ–

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dpkg-scanpackages
      run: sudo apt-get update && sudo apt-get install -y dpkg-dev

    - name: Ensure script has execute permissions
      run: chmod +x ./generate_packages.sh

    - name: Run generate_packages.sh
      run: bash ./generate_packages.sh

    - name: Commit and push updated Packages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add Packages Packages.bz2 Packages.gz Release
        git commit -m "Update Packages files"
        git push origin main

    - name: Create Release file
      run: |
        echo "Origin: ðŸ’«Axs proâœ¨" > Release
        echo "Label: ðŸ’«Axs proâœ¨" >> Release
        echo "Suite: stable" >> Release
        echo "Version: 1.0" >> Release
        echo "Codename: ðŸ’«Axs proâœ¨" >> Release
        echo "Architectures: iphoneos-arm64 iphoneos-arm64e" >> Release
        echo "Components: main" >> Release
        echo "Description: è‡ªç”¨æ’ä»¶åˆ†äº«ï¼Œæœ‰é—®é¢˜è¯·å¸è½½ï¼ï¼ï¼" >> Release
